<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Datum extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Datum_model');
    } 

    /*
     * Listing of data
     */
    function index()
    {
        $data['data'] = $this->Datum_model->get_all_data();

        $this->load->view('datum/index',$data);
    }

    /*
     * Adding a new datum
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'data_payload' => $this->input->post('data_payload'),
            );
            
            $datum_id = $this->Datum_model->add_datum($params);
            redirect('datum/index');
        }
        else
        {
            $this->load->view('datum/add');
        }
    }  

    /*
     * Editing a datum
     */
    function edit($sid)
    {   
        // check if the datum exists before trying to edit it
        $datum = $this->Datum_model->get_datum($sid);
        
        if(isset($datum['sid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'data_payload' => $this->input->post('data_payload'),
                );

                $this->Datum_model->update_datum($sid,$params);            
                redirect('datum/index');
            }
            else
            {   
                $data['datum'] = $this->Datum_model->get_datum($sid);
    
                $this->load->view('datum/edit',$data);
            }
        }
        else
            show_error('The datum you are trying to edit does not exist.');
    } 

    /*
     * Deleting datum
     */
    function remove($sid)
    {
        $datum = $this->Datum_model->get_datum($sid);

        // check if the datum exists before trying to delete it
        if(isset($datum['sid']))
        {
            $this->Datum_model->delete_datum($sid);
            redirect('datum/index');
        }
        else
            show_error('The datum you are trying to delete does not exist.');
    }
    
}
