<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Detail extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detail_model');
    } 

    /*
     * Listing of detail
     */
    function index()
    {
        $data['detail'] = $this->Detail_model->get_all_detail();

        $this->load->view('detail/index',$data);
    }

    /*
     * Adding a new detail
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'detail_text' => $this->input->post('detail_text'),
            );
            
            $detail_id = $this->Detail_model->add_detail($params);
            redirect('detail/index');
        }
        else
        {
            $this->load->view('detail/add');
        }
    }  

    /*
     * Editing a detail
     */
    function edit($detail_type)
    {   
        // check if the detail exists before trying to edit it
        $detail = $this->Detail_model->get_detail($detail_type);
        
        if(isset($detail['detail_type']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'detail_text' => $this->input->post('detail_text'),
                );

                $this->Detail_model->update_detail($detail_type,$params);            
                redirect('detail/index');
            }
            else
            {   
                $data['detail'] = $this->Detail_model->get_detail($detail_type);
    
                $this->load->view('detail/edit',$data);
            }
        }
        else
            show_error('The detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting detail
     */
    function remove($detail_type)
    {
        $detail = $this->Detail_model->get_detail($detail_type);

        // check if the detail exists before trying to delete it
        if(isset($detail['detail_type']))
        {
            $this->Detail_model->delete_detail($detail_type);
            redirect('detail/index');
        }
        else
            show_error('The detail you are trying to delete does not exist.');
    }
    
}
