<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Icmphdr extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Icmphdr_model');
    } 

    /*
     * Listing of icmphdr
     */
    function index()
    {
        $data['icmphdr'] = $this->Icmphdr_model->get_all_icmphdr();

        $this->load->view('icmphdr/index',$data);
    }

    /*
     * Adding a new icmphdr
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'icmp_type' => $this->input->post('icmp_type'),
				'icmp_code' => $this->input->post('icmp_code'),
				'icmp_csum' => $this->input->post('icmp_csum'),
				'icmp_id' => $this->input->post('icmp_id'),
				'icmp_seq' => $this->input->post('icmp_seq'),
            );
            
            $icmphdr_id = $this->Icmphdr_model->add_icmphdr($params);
            redirect('icmphdr/index');
        }
        else
        {
            $this->load->view('icmphdr/add');
        }
    }  

    /*
     * Editing a icmphdr
     */
    function edit($sid)
    {   
        // check if the icmphdr exists before trying to edit it
        $icmphdr = $this->Icmphdr_model->get_icmphdr($sid);
        
        if(isset($icmphdr['sid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'icmp_type' => $this->input->post('icmp_type'),
					'icmp_code' => $this->input->post('icmp_code'),
					'icmp_csum' => $this->input->post('icmp_csum'),
					'icmp_id' => $this->input->post('icmp_id'),
					'icmp_seq' => $this->input->post('icmp_seq'),
                );

                $this->Icmphdr_model->update_icmphdr($sid,$params);            
                redirect('icmphdr/index');
            }
            else
            {   
                $data['icmphdr'] = $this->Icmphdr_model->get_icmphdr($sid);
    
                $this->load->view('icmphdr/edit',$data);
            }
        }
        else
            show_error('The icmphdr you are trying to edit does not exist.');
    } 

    /*
     * Deleting icmphdr
     */
    function remove($sid)
    {
        $icmphdr = $this->Icmphdr_model->get_icmphdr($sid);

        // check if the icmphdr exists before trying to delete it
        if(isset($icmphdr['sid']))
        {
            $this->Icmphdr_model->delete_icmphdr($sid);
            redirect('icmphdr/index');
        }
        else
            show_error('The icmphdr you are trying to delete does not exist.');
    }
    
}
