<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Iphdr extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Iphdr_model');
    } 

    /*
     * Listing of iphdr
     */
    function index()
    {
        $data['iphdr'] = $this->Iphdr_model->get_all_iphdr();

        $this->load->view('iphdr/index',$data);
    }

    /*
     * Adding a new iphdr
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ip_src' => $this->input->post('ip_src'),
				'ip_dst' => $this->input->post('ip_dst'),
				'ip_ver' => $this->input->post('ip_ver'),
				'ip_hlen' => $this->input->post('ip_hlen'),
				'ip_tos' => $this->input->post('ip_tos'),
				'ip_len' => $this->input->post('ip_len'),
				'ip_id' => $this->input->post('ip_id'),
				'ip_flags' => $this->input->post('ip_flags'),
				'ip_off' => $this->input->post('ip_off'),
				'ip_ttl' => $this->input->post('ip_ttl'),
				'ip_proto' => $this->input->post('ip_proto'),
				'ip_csum' => $this->input->post('ip_csum'),
            );
            
            $iphdr_id = $this->Iphdr_model->add_iphdr($params);
            redirect('iphdr/index');
        }
        else
        {
            $this->load->view('iphdr/add');
        }
    }  

    /*
     * Editing a iphdr
     */
    function edit($sid)
    {   
        // check if the iphdr exists before trying to edit it
        $iphdr = $this->Iphdr_model->get_iphdr($sid);
        
        if(isset($iphdr['sid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ip_src' => $this->input->post('ip_src'),
					'ip_dst' => $this->input->post('ip_dst'),
					'ip_ver' => $this->input->post('ip_ver'),
					'ip_hlen' => $this->input->post('ip_hlen'),
					'ip_tos' => $this->input->post('ip_tos'),
					'ip_len' => $this->input->post('ip_len'),
					'ip_id' => $this->input->post('ip_id'),
					'ip_flags' => $this->input->post('ip_flags'),
					'ip_off' => $this->input->post('ip_off'),
					'ip_ttl' => $this->input->post('ip_ttl'),
					'ip_proto' => $this->input->post('ip_proto'),
					'ip_csum' => $this->input->post('ip_csum'),
                );

                $this->Iphdr_model->update_iphdr($sid,$params);            
                redirect('iphdr/index');
            }
            else
            {   
                $data['iphdr'] = $this->Iphdr_model->get_iphdr($sid);
    
                $this->load->view('iphdr/edit',$data);
            }
        }
        else
            show_error('The iphdr you are trying to edit does not exist.');
    } 

    /*
     * Deleting iphdr
     */
    function remove($sid)
    {
        $iphdr = $this->Iphdr_model->get_iphdr($sid);

        // check if the iphdr exists before trying to delete it
        if(isset($iphdr['sid']))
        {
            $this->Iphdr_model->delete_iphdr($sid);
            redirect('iphdr/index');
        }
        else
            show_error('The iphdr you are trying to delete does not exist.');
    }
    
}
