<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Opt extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Opt_model');
    } 

    /*
     * Listing of opt
     */
    function index()
    {
        $data['opt'] = $this->Opt_model->get_all_opt();

        $this->load->view('opt/index',$data);
    }

    /*
     * Adding a new opt
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'opt_proto' => $this->input->post('opt_proto'),
				'opt_code' => $this->input->post('opt_code'),
				'opt_len' => $this->input->post('opt_len'),
				'opt_data' => $this->input->post('opt_data'),
            );
            
            $opt_id = $this->Opt_model->add_opt($params);
            redirect('opt/index');
        }
        else
        {
            $this->load->view('opt/add');
        }
    }  

    /*
     * Editing a opt
     */
    function edit($sid)
    {   
        // check if the opt exists before trying to edit it
        $opt = $this->Opt_model->get_opt($sid);
        
        if(isset($opt['sid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'opt_proto' => $this->input->post('opt_proto'),
					'opt_code' => $this->input->post('opt_code'),
					'opt_len' => $this->input->post('opt_len'),
					'opt_data' => $this->input->post('opt_data'),
                );

                $this->Opt_model->update_opt($sid,$params);            
                redirect('opt/index');
            }
            else
            {   
                $data['opt'] = $this->Opt_model->get_opt($sid);
    
                $this->load->view('opt/edit',$data);
            }
        }
        else
            show_error('The opt you are trying to edit does not exist.');
    } 

    /*
     * Deleting opt
     */
    function remove($sid)
    {
        $opt = $this->Opt_model->get_opt($sid);

        // check if the opt exists before trying to delete it
        if(isset($opt['sid']))
        {
            $this->Opt_model->delete_opt($sid);
            redirect('opt/index');
        }
        else
            show_error('The opt you are trying to delete does not exist.');
    }
    
}
