<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Reference extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reference_model');
    } 

    /*
     * Listing of reference
     */
    function index()
    {
        $data['reference'] = $this->Reference_model->get_all_reference();

        $this->load->view('reference/index',$data);
    }

    /*
     * Adding a new reference
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ref_system_id' => $this->input->post('ref_system_id'),
				'ref_tag' => $this->input->post('ref_tag'),
            );
            
            $reference_id = $this->Reference_model->add_reference($params);
            redirect('reference/index');
        }
        else
        {
            $this->load->view('reference/add');
        }
    }  

    /*
     * Editing a reference
     */
    function edit($ref_id)
    {   
        // check if the reference exists before trying to edit it
        $reference = $this->Reference_model->get_reference($ref_id);
        
        if(isset($reference['ref_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ref_system_id' => $this->input->post('ref_system_id'),
					'ref_tag' => $this->input->post('ref_tag'),
                );

                $this->Reference_model->update_reference($ref_id,$params);            
                redirect('reference/index');
            }
            else
            {   
                $data['reference'] = $this->Reference_model->get_reference($ref_id);
    
                $this->load->view('reference/edit',$data);
            }
        }
        else
            show_error('The reference you are trying to edit does not exist.');
    } 

    /*
     * Deleting reference
     */
    function remove($ref_id)
    {
        $reference = $this->Reference_model->get_reference($ref_id);

        // check if the reference exists before trying to delete it
        if(isset($reference['ref_id']))
        {
            $this->Reference_model->delete_reference($ref_id);
            redirect('reference/index');
        }
        else
            show_error('The reference you are trying to delete does not exist.');
    }
    
}
