<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Reference_system extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reference_system_model');
    } 

    /*
     * Listing of reference_system
     */
    function index()
    {
        $data['reference_system'] = $this->Reference_system_model->get_all_reference_system();

        $this->load->view('reference_system/index',$data);
    }

    /*
     * Adding a new reference_system
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ref_system_name' => $this->input->post('ref_system_name'),
            );
            
            $reference_system_id = $this->Reference_system_model->add_reference_system($params);
            redirect('reference_system/index');
        }
        else
        {
            $this->load->view('reference_system/add');
        }
    }  

    /*
     * Editing a reference_system
     */
    function edit($ref_system_id)
    {   
        // check if the reference_system exists before trying to edit it
        $reference_system = $this->Reference_system_model->get_reference_system($ref_system_id);
        
        if(isset($reference_system['ref_system_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ref_system_name' => $this->input->post('ref_system_name'),
                );

                $this->Reference_system_model->update_reference_system($ref_system_id,$params);            
                redirect('reference_system/index');
            }
            else
            {   
                $data['reference_system'] = $this->Reference_system_model->get_reference_system($ref_system_id);
    
                $this->load->view('reference_system/edit',$data);
            }
        }
        else
            show_error('The reference_system you are trying to edit does not exist.');
    } 

    /*
     * Deleting reference_system
     */
    function remove($ref_system_id)
    {
        $reference_system = $this->Reference_system_model->get_reference_system($ref_system_id);

        // check if the reference_system exists before trying to delete it
        if(isset($reference_system['ref_system_id']))
        {
            $this->Reference_system_model->delete_reference_system($ref_system_id);
            redirect('reference_system/index');
        }
        else
            show_error('The reference_system you are trying to delete does not exist.');
    }
    
}
