<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Schema extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Schema_model');
    } 

    /*
     * Listing of schema
     */
    function index()
    {
        $data['schema'] = $this->Schema_model->get_all_schema();

        $this->load->view('schema/index',$data);
    }

    /*
     * Adding a new schema
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $schema_id = $this->Schema_model->add_schema($params);
            redirect('schema/index');
        }
        else
        {
            $this->load->view('schema/add');
        }
    }  

    /*
     * Editing a schema
     */
    function edit($)
    {   
        // check if the schema exists before trying to edit it
        $schema = $this->Schema_model->get_schema($);
        
        if(isset($schema['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Schema_model->update_schema($,$params);            
                redirect('schema/index');
            }
            else
            {   
                $data['schema'] = $this->Schema_model->get_schema($);
    
                $this->load->view('schema/edit',$data);
            }
        }
        else
            show_error('The schema you are trying to edit does not exist.');
    } 

    /*
     * Deleting schema
     */
    function remove($)
    {
        $schema = $this->Schema_model->get_schema($);

        // check if the schema exists before trying to delete it
        if(isset($schema['']))
        {
            $this->Schema_model->delete_schema($);
            redirect('schema/index');
        }
        else
            show_error('The schema you are trying to delete does not exist.');
    }
    
}
