<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Datum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get datum by sid
     */
    function get_datum($sid)
    {
        return $this->db->get_where('data',array('sid'=>$sid))->row_array();
    }
    
    /*
     * Get all data
     */
    function get_all_data()
    {
        return $this->db->get('data')->result_array();
    }
    
    /*
     * function to add new datum
     */
    function add_datum($params)
    {
        $this->db->insert('data',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update datum
     */
    function update_datum($sid,$params)
    {
        $this->db->where('sid',$sid);
        $response = $this->db->update('data',$params);
        if($response)
        {
            return "datum updated successfully";
        }
        else
        {
            return "Error occuring while updating datum";
        }
    }
    
    /*
     * function to delete datum
     */
    function delete_datum($sid)
    {
        $response = $this->db->delete('data',array('sid'=>$sid));
        if($response)
        {
            return "datum deleted successfully";
        }
        else
        {
            return "Error occuring while deleting datum";
        }
    }
}
