<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detail by detail_type
     */
    function get_detail($detail_type)
    {
        return $this->db->get_where('detail',array('detail_type'=>$detail_type))->row_array();
    }
    
    /*
     * Get all detail
     */
    function get_all_detail()
    {
        return $this->db->get('detail')->result_array();
    }
    
    /*
     * function to add new detail
     */
    function add_detail($params)
    {
        $this->db->insert('detail',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detail
     */
    function update_detail($detail_type,$params)
    {
        $this->db->where('detail_type',$detail_type);
        $response = $this->db->update('detail',$params);
        if($response)
        {
            return "detail updated successfully";
        }
        else
        {
            return "Error occuring while updating detail";
        }
    }
    
    /*
     * function to delete detail
     */
    function delete_detail($detail_type)
    {
        $response = $this->db->delete('detail',array('detail_type'=>$detail_type));
        if($response)
        {
            return "detail deleted successfully";
        }
        else
        {
            return "Error occuring while deleting detail";
        }
    }
}
