<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Event_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get event by sid
     */
    function get_event($sid)
    {
        return $this->db->get_where('event',array('sid'=>$sid))->row_array();
    }
    
    /*
     * Get all event
     */
    function get_all_event()
    {
        return $this->db->get('event')->result_array();
    }
    
    /*
     * function to add new event
     */
    function add_event($params)
    {
        $this->db->insert('event',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update event
     */
    function update_event($sid,$params)
    {
        $this->db->where('sid',$sid);
        $response = $this->db->update('event',$params);
        if($response)
        {
            return "event updated successfully";
        }
        else
        {
            return "Error occuring while updating event";
        }
    }
    
    /*
     * function to delete event
     */
    function delete_event($sid)
    {
        $response = $this->db->delete('event',array('sid'=>$sid));
        if($response)
        {
            return "event deleted successfully";
        }
        else
        {
            return "Error occuring while deleting event";
        }
    }
}
