<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Opt_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get opt by sid
     */
    function get_opt($sid)
    {
        return $this->db->get_where('opt',array('sid'=>$sid))->row_array();
    }
    
    /*
     * Get all opt
     */
    function get_all_opt()
    {
        return $this->db->get('opt')->result_array();
    }
    
    /*
     * function to add new opt
     */
    function add_opt($params)
    {
        $this->db->insert('opt',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update opt
     */
    function update_opt($sid,$params)
    {
        $this->db->where('sid',$sid);
        $response = $this->db->update('opt',$params);
        if($response)
        {
            return "opt updated successfully";
        }
        else
        {
            return "Error occuring while updating opt";
        }
    }
    
    /*
     * function to delete opt
     */
    function delete_opt($sid)
    {
        $response = $this->db->delete('opt',array('sid'=>$sid));
        if($response)
        {
            return "opt deleted successfully";
        }
        else
        {
            return "Error occuring while deleting opt";
        }
    }
}
