<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Reference_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reference by ref_id
     */
    function get_reference($ref_id)
    {
        return $this->db->get_where('reference',array('ref_id'=>$ref_id))->row_array();
    }
    
    /*
     * Get all reference
     */
    function get_all_reference()
    {
        return $this->db->get('reference')->result_array();
    }
    
    /*
     * function to add new reference
     */
    function add_reference($params)
    {
        $this->db->insert('reference',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reference
     */
    function update_reference($ref_id,$params)
    {
        $this->db->where('ref_id',$ref_id);
        $response = $this->db->update('reference',$params);
        if($response)
        {
            return "reference updated successfully";
        }
        else
        {
            return "Error occuring while updating reference";
        }
    }
    
    /*
     * function to delete reference
     */
    function delete_reference($ref_id)
    {
        $response = $this->db->delete('reference',array('ref_id'=>$ref_id));
        if($response)
        {
            return "reference deleted successfully";
        }
        else
        {
            return "Error occuring while deleting reference";
        }
    }
}
