<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Schema_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get schema by 
     */
    function get_schema($)
    {
        return $this->db->get_where('schema',array(''=>$))->row_array();
    }
    
    /*
     * Get all schema
     */
    function get_all_schema()
    {
        return $this->db->get('schema')->result_array();
    }
    
    /*
     * function to add new schema
     */
    function add_schema($params)
    {
        $this->db->insert('schema',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update schema
     */
    function update_schema($,$params)
    {
        $this->db->where('',$);
        $response = $this->db->update('schema',$params);
        if($response)
        {
            return "schema updated successfully";
        }
        else
        {
            return "Error occuring while updating schema";
        }
    }
    
    /*
     * function to delete schema
     */
    function delete_schema($)
    {
        $response = $this->db->delete('schema',array(''=>$));
        if($response)
        {
            return "schema deleted successfully";
        }
        else
        {
            return "Error occuring while deleting schema";
        }
    }
}
